# Generated by Django 3.1.7 on 2021-05-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order1',
            new_name='Order12',
        ),
    ]
