# Generated by Django 3.1.7 on 2021-05-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210513_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order12',
            old_name='product_category',
            new_name='product_name',
        ),
    ]
