# Generated by Django 3.1.7 on 2021-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('complaint', models.CharField(max_length=1500)),
            ],
        ),
    ]
