# Generated by Django 3.1.7 on 2021-05-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
